name: Publish Package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24
          registry-url: 'https://npm.pkg.github.com'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '.ruby-version'
          bundler-cache: true

      - name: Install dependencies, lint and jest test
        run: | 
          chmod +x ./.ci_steps/test.sh
          ./.ci_steps/test.sh

      - name: Run Prepack Script
        run: npm run prepack

      - name: Publish
        run: |
          VERSION=$(node -p "require('./package.json').version")

          if [[ "$VERSION" == *"-alpha."* ]]; then
            npm publish --tag alpha
          elif [[ "$VERSION" == *"-beta."* ]]; then
            npm publish --tag beta
          elif [[ "$VERSION" == *"-rc."* ]]; then
            npm publish --tag rc
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
